### PR TITLE
Added ceph-mgr integration analysis with Tendrl

### PR DESCRIPTION
**Pull request by shtripat**
Signed-off-by: Shubhendu <shtripat@redhat.com>

### CODE REVIEW

**Comment by shtripat** [comment]
@brainfunked As suggested created this pull request. please review and close

**Comment by mbukatov** [comment]
Do we have some feedback from ceph community already, or do we plan to get some after this is merged?

**Comment by mbukatov** [comment]
Related to https://github.com/ceph/ceph/pull/14457

**Comment by mbukatov** [comment]
Why is this stalled?

**Review by r0h4n — APPROVED** [review]

**Pull request closed without merging**
