### PR TITLE
Frontend documentation

### PR DESCRIPTION
**Pull request by debloper**
Added development and deployment docs for @Tendrl/tendrl_frontend.

### CODE REVIEW

**Comment by fbalak** [comment]
I tried to install UI with your installation guide. I ran into problem when I called # npm install

```
npm WARN enoent ENOENT: no such file or directory, open '/root/local/tendrl_frontend/package.json'
npm WARN tendrl_frontend No description
npm WARN tendrl_frontend No repository field.
npm WARN tendrl_frontend No README data
npm WARN tendrl_frontend No license field.
```

**Comment by fbalak** [comment]
When called # tsd install

```
-> running install

>> written zero files
```

**Comment by debloper** [comment]
@fbalak updated commit to point to working repo (till migrated), should work as intended.
Also, `$ tsd install` will only work properly after a successful `$ npm install`

**Comment by debloper** [comment]
@r0h4n any feedback? If there's no blocker, can we please merge this?

**Comment by debloper** [comment]
Fixed with Tendrl/tendrl_frontend#35

**Pull request closed without merging**
