### PR TITLE
Ceph-mgr integration proposal

### PR DESCRIPTION
**Pull request by shtripat**
Added below images
- ceph-mgr-arch.png
- tendrl-ceph-mgr-rest.png
- tendrl-ceph-mgr-python-mod.png

Signed-off-by: Shubhendu shtripat@redhat.com

### CODE REVIEW

**Comment by brainfunked** [comment]
Please add a writeup under the `proposals` directory to tie the images to a narrative.

Some additional questions to be answered in the document:
- Would be possible and if yes, more efficient, for the ceph mgr python module to act as the state bridge directly? This means that the module would translate the in-memory representation of ceph's state into tendrl's central store.
- How would the ceph mgr module keep updating tendrl (either directly into the central store or via some communication with the state bridge) about the updates in the cluster?
- Is it possible to detect in-flight operations in a ceph cluster via manager?
- Does the manager provide any functionality to act as a gateway through which operations could be invoked on the cluster?
- If there's no gateway functionality provided by ceph manager, would it mean that tendrl would need a separate operations bridge for ceph? How would this bridge invoke operations on the cluster?

**Comment by shtripat** [comment]
Do you mean to create a proposals dir under /Tendrl/documentation and add an entry there for usage of ceph-mgr?

I would try to update the github issue with answers to the questions raised here.

**Comment by shtripat** [comment]
@brainfunked 
BTW the images in this patch are referred from #28 .
The item #28 is marked as future planned item. Do we still need a proposals dir to talk about and link these images?

**Comment by brainfunked** [comment]
@shtripat Yes, this ends up being a future integration. For now, I think the best way to put it up for now is under proposals. In the future, we'll figure out some better way to handle this. In any case, we do need a narrative.

**Comment by shtripat** [comment]
@brainfunked I have moved the images to proposals dir and added some explaination about them in commit message.

The above mentioned questions, I would rather add to github issue #28 and add the answers there so all the documentation we have in one place.

**Comment by shtripat** [comment]
@brainfunked can you review and approve this?

**Review by r0h4n — APPROVED** [review]

**Pull request merged**
